### ISSUE TITLE
Test suite does not compile on Mac with clang

### ISSUE THREAD

**Issue by mjdemilliano** [Embedded-AMS/EmbeddedProto#1]
The test suite does not compile on Mac 10.14.6 with clang.

Steps to reproduce:

    git clone --recursive https://github.com/Embedded-AMS/EmbeddedProto
    cd EmbeddedProto
    python3.7 -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt
    ./build_test.sh

Enviroment:

 - Mac OSX 10.14.6
 - Shell: zsh or bash
 - Compiler:

```
$ c++ -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

First errors (there are many more):

```
[ 86%] Building CXX object CMakeFiles/test_EmbeddedProto.dir/test/test_string_bytes.o
[ 91%] Building CXX object CMakeFiles/test_EmbeddedProto.dir/test/test_oneof_fields.o
In file included from /var/folders/vd/wr3sq1gn4vl6z129hcs5_kz00000gn/T/tmp.p8ASoSEH/EmbeddedProto/src/Fields.cpp:31:
In file included from /var/folders/vd/wr3sq1gn4vl6z129hcs5_kz00000gn/T/tmp.p8ASoSEH/EmbeddedProto/src/Fields.h:35:
/var/folders/vd/wr3sq1gn4vl6z129hcs5_kz00000gn/T/tmp.p8ASoSEH/EmbeddedProto/src/WireFormatter.h:259:19: error: function 'ZigZagDecode<unsigned long long>' with deduced return type cannot be used before it
      is defined
          value = ZigZagDecode(uint_value);
                  ^
/var/folders/vd/wr3sq1gn4vl6z129hcs5_kz00000gn/T/tmp.p8ASoSEH/EmbeddedProto/src/WireFormatter.h:482:29: note: 'ZigZagDecode<unsigned long long>' declared here
      static constexpr auto ZigZagDecode(const UINT_TYPE n) 
                            ^
/var/folders/vd/wr3sq1gn4vl6z129hcs5_kz00000gn/T/tmp.p8ASoSEH/EmbeddedProto/src/WireFormatter.h:416:75: error: no member named 'ceil' in namespace 'std'; did you mean simply 'ceil'?
        static constexpr uint8_t N_BYTES_IN_VARINT = static_cast<uint8_t>(std::ceil(
                                                                          ^~~~~~~~~
                                                                          ceil
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:841:1: note: 'ceil' declared here
ceil(_A1 __lcpp_x) _NOEXCEPT {return ::ceil((double)__lcpp_x);}
^
```

Full log attached.
[EmbeddedProto-mac-compilation-error-log.txt](https://github.com/Embedded-AMS/EmbeddedProto/files/4761120/EmbeddedProto-mac-compilation-error-log.txt)

**Comment by BartHertog** [comment]
Hi mjdemilliano,

Thank you for reporting this. We will address the problem.

**Comment by BartHertog** [comment]
The issues you mentioned could be reproduced suing clang-9 and clang++-9. Those have been resolved and merged into develop.
